/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author MarcoVi
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCalendario = new javax.swing.JButton();
        btnComprobantes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/registrar_1.png"))); // NOI18N
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/registrar_1.png"))); // NOI18N
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/registrar_2.png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 290, 70));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 80, 0, -1));

        btnCalendario.setBackground(new java.awt.Color(255, 255, 255));
        btnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Calendario_1.png"))); // NOI18N
        btnCalendario.setBorder(null);
        btnCalendario.setBorderPainted(false);
        btnCalendario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Calendario_1.png"))); // NOI18N
        btnCalendario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Calendario_2.png"))); // NOI18N
        jPanel1.add(btnCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 300, 70));

        btnComprobantes.setBackground(new java.awt.Color(255, 255, 255));
        btnComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Comprobante_1.png"))); // NOI18N
        btnComprobantes.setBorder(null);
        btnComprobantes.setBorderPainted(false);
        btnComprobantes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Comprobante_1.png"))); // NOI18N
        btnComprobantes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Comprobante_2.png"))); // NOI18N
        jPanel1.add(btnComprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 320, 70));

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Reportes_1png.png"))); // NOI18N
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Reportes_1png.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Reportes_2png.png"))); // NOI18N
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 320, 100));

        btnCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/CrearUsuario_1.png"))); // NOI18N
        btnCrearUsuario.setBorder(null);
        btnCrearUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/CrearUsuario_1.png"))); // NOI18N
        btnCrearUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/CrearUsuario_2.png"))); // NOI18N
        jPanel1.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 290, 90));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/salir_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/salir_1.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/salir_2.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 290, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Menu principal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendario;
    private javax.swing.JButton btnComprobantes;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
