package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class VistaGestionEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionEmpleadow
     */
    public VistaGestionEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGestionEmpleado().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialogo_Empleado = new javax.swing.JDialog();
        txtCodigo_Act = new javax.swing.JTextField();
        txtCedula_Act = new javax.swing.JTextField();
        txtNombres_Act = new javax.swing.JTextField();
        txtApellidos_Act = new javax.swing.JTextField();
        txtDireccion_Act = new javax.swing.JTextField();
        txtCorreo_Desc = new javax.swing.JTextField();
        txtTelefono_Act = new javax.swing.JTextField();
        txtCelular_Act = new javax.swing.JTextField();
        txtCargo_Act = new javax.swing.JTextField();
        txtSueldo_ACT = new javax.swing.JTextField();
        txtUsuario_Act = new javax.swing.JTextField();
        txtClave_Act = new javax.swing.JTextField();
        btnGrabar_Act = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtBusqueda = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCedula1 = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar2 = new javax.swing.JButton();

        Dialogo_Empleado.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Dialogo_Empleado.getContentPane().add(txtCodigo_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, -1));
        Dialogo_Empleado.getContentPane().add(txtCedula_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));
        Dialogo_Empleado.getContentPane().add(txtNombres_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtApellidos_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtDireccion_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtCorreo_Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtTelefono_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtCelular_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtCargo_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtSueldo_ACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 170, -1));
        Dialogo_Empleado.getContentPane().add(txtUsuario_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 170, 20));

        txtClave_Act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClave_ActActionPerformed(evt);
            }
        });
        Dialogo_Empleado.getContentPane().add(txtClave_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 160, -1));

        btnGrabar_Act.setText("jButton1");
        Dialogo_Empleado.getContentPane().add(btnGrabar_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Actualizar_Empleado.png"))); // NOI18N
        Dialogo_Empleado.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setBorder(null);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 50, 20));

        txtApellido.setBorder(null);
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 164, 160, 20));

        txtDireccion.setBorder(null);
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 201, 160, 20));

        txtCorreo.setBorder(null);
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 232, 160, 20));

        txtTelefono.setBorder(null);
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 268, 160, 20));

        txtCelular.setBorder(null);
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 306, 160, 20));

        txtCargo.setBorder(null);
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, 20));

        txtSueldo.setBorder(null);
        getContentPane().add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 377, 160, 20));

        txtUsuario.setBorder(null);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 160, 20));

        txtClave.setBorder(null);
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 444, 160, 20));

        txtBusqueda.setBorder(null);
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 240, 20));

        txtNombre.setBorder(null);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, 20));

        txtCedula1.setBorder(null);
        getContentPane().add(txtCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, 20));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/btnElimi.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 130, 40));

        btnEliminar.setBackground(new java.awt.Color(32, 156, 162));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/btnElimi.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 130, 40));

        btnGuardar1.setBackground(new java.awt.Color(32, 156, 162));
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/btnG.png"))); // NOI18N
        btnGuardar1.setBorder(null);
        btnGuardar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 480, -1, 30));

        btnActualizar.setBackground(new java.awt.Color(32, 156, 162));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/btnAct.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, 40));

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cedula", "Nombres", "Apellidos", "Direccion", "Correo", "Telefono", "Celular", "Cargo", "Sueldo", "Usuario", "Clave"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaEmpleados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 720, 310));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 230, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/GestionEmpl.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        btnGuardar2.setBackground(new java.awt.Color(32, 156, 162));
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/btnG.png"))); // NOI18N
        btnGuardar2.setBorder(null);
        btnGuardar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtClave_ActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClave_ActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClave_ActActionPerformed

    public JTable getTablaEmpleados() {
        return TablaEmpleados;
    }

    public void setTablaEmpleados(JTable TablaEmpleados) {
        this.TablaEmpleados = TablaEmpleados;
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public void setBtnActualizar(JButton btnActualizar) {
        this.btnActualizar = btnActualizar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnGuardar1() {
        return btnGuardar1;
    }

    public void setBtnGuardar1(JButton btnGuardar1) {
        this.btnGuardar1 = btnGuardar1;
    }

    public JButton getBtnGuardar2() {
        return btnGuardar2;
    }

    public void setBtnGuardar2(JButton btnGuardar2) {
        this.btnGuardar2 = btnGuardar2;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JTextField getTxtBusqueda() {
        return txtBusqueda;
    }

    public void setTxtBusqueda(JTextField txtBusqueda) {
        this.txtBusqueda = txtBusqueda;
    }

    public JTextField getTxtCargo() {
        return txtCargo;
    }

    public void setTxtCargo(JTextField txtCargo) {
        this.txtCargo = txtCargo;
    }

    public JTextField getTxtCedula1() {
        return txtCedula1;
    }

    public void setTxtCedula1(JTextField txtCedula1) {
        this.txtCedula1 = txtCedula1;
    }

    public JTextField getTxtCelular() {
        return txtCelular;
    }

    public void setTxtCelular(JTextField txtCelular) {
        this.txtCelular = txtCelular;
    }

    public JTextField getTxtClave() {
        return txtClave;
    }

    public void setTxtClave(JTextField txtClave) {
        this.txtClave = txtClave;
    }

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCodigo = txtCodigo;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtSueldo() {
        return txtSueldo;
    }

    public void setTxtSueldo(JTextField txtSueldo) {
        this.txtSueldo = txtSueldo;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }
    
    public JDialog getDialogo_Empleado() {
        return Dialogo_Empleado;
    }

    //COMPONENTES DIALOGO ACTUALIZAR
    public void setDialogo_Empleado(JDialog Dialogo_Empleado) {
        this.Dialogo_Empleado = Dialogo_Empleado;
    }

    public JButton getBtnGrabar_Act() {
        return btnGrabar_Act;
    }

    public void setBtnGrabar_Act(JButton btnGrabar_Act) {
        this.btnGrabar_Act = btnGrabar_Act;
    }

   

    public JTextField getTxtApellidos_Act() {
        return txtApellidos_Act;
    }

    public void setTxtApellidos_Act(JTextField txtApellidos_Act) {
        this.txtApellidos_Act = txtApellidos_Act;
    }

    public JTextField getTxtCargo_Act() {
        return txtCargo_Act;
    }

    public void setTxtCargo_Act(JTextField txtCargo_Act) {
        this.txtCargo_Act = txtCargo_Act;
    }

    public JTextField getTxtCedula_Act() {
        return txtCedula_Act;
    }

    public void setTxtCedula_Act(JTextField txtCedula_Act) {
        this.txtCedula_Act = txtCedula_Act;
    }

    public JTextField getTxtCelular_Act() {
        return txtCelular_Act;
    }

    public void setTxtCelular_Act(JTextField txtCelular_Act) {
        this.txtCelular_Act = txtCelular_Act;
    }

    public JTextField getTxtClave_Act() {
        return txtClave_Act;
    }

    public void setTxtClave_Act(JTextField txtClave_Act) {
        this.txtClave_Act = txtClave_Act;
    }

    public JTextField getTxtCodigo_Act() {
        return txtCodigo_Act;
    }

    public void setTxtCodigo_Act(JTextField txtCodigo_Act) {
        this.txtCodigo_Act = txtCodigo_Act;
    }

    public JTextField getTxtCorreo_Desc() {
        return txtCorreo_Desc;
    }

    public void setTxtCorreo_Desc(JTextField txtCorreo_Desc) {
        this.txtCorreo_Desc = txtCorreo_Desc;
    }

    public JTextField getTxtDireccion_Act() {
        return txtDireccion_Act;
    }

    public void setTxtDireccion_Act(JTextField txtDireccion_Act) {
        this.txtDireccion_Act = txtDireccion_Act;
    }

    public JTextField getTxtNombres_Act() {
        return txtNombres_Act;
    }

    public void setTxtNombres_Act(JTextField txtNombres_Act) {
        this.txtNombres_Act = txtNombres_Act;
    }

    public JTextField getTxtSueldo_ACT() {
        return txtSueldo_ACT;
    }

    public void setTxtSueldo_ACT(JTextField txtSueldo_ACT) {
        this.txtSueldo_ACT = txtSueldo_ACT;
    }

    public JTextField getTxtTelefono_Act() {
        return txtTelefono_Act;
    }

    public void setTxtTelefono_Act(JTextField txtTelefono_Act) {
        this.txtTelefono_Act = txtTelefono_Act;
    }

    public JTextField getTxtUsuario_Act() {
        return txtUsuario_Act;
    }

    public void setTxtUsuario_Act(JTextField txtUsuario_Act) {
        this.txtUsuario_Act = txtUsuario_Act;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialogo_Empleado;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar_Act;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidos_Act;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCargo_Act;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JTextField txtCedula_Act;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCelular_Act;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClave_Act;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo_Act;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo_Desc;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion_Act;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombres_Act;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSueldo_ACT;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono_Act;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario_Act;
    // End of variables declaration//GEN-END:variables
}
